//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.22 at 03:10:14 PM AST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://mySchool/students", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package myschool.students;
